### ISSUE TITLE
Investigate css variables to support multiple themes

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#302]
```scss
body.theme-1 {
  --primary-color: red;
}

body.theme-2 {
  --primary-color: blue;
}

$primary-color: var(--primary-color); // For cleaner usage still use scss variable to wrap

// In use

.my-content {
    background-color: $primary-color;
}
```
